<?php require_once __DIR__ . '/../includes/init.php'; includeHeader('Start Selling - FezaMarket Help'); ?>
<div class="container"><div class="help-header"><h1>Start Selling</h1><p>Begin your seller journey</p></div><div class="help-content">

<section class="help-section"><h2>Becoming a Seller</h2><div class="steps">
<div class="step"><div class="step-number">1</div><h3>Register</h3><p>Create a seller account with business information.</p></div>
<div class="step"><div class="step-number">2</div><h3>Verify</h3><p>Complete identity verification and set up payments.</p></div>
<div class="step"><div class="step-number">3</div><h3>List Products</h3><p>Create your first product listings with photos.</p></div>
<div class="step"><div class="step-number">4</div><h3>Start Selling</h3><p>Manage orders and grow your business.</p></div>
</div></section>
<div class="cta-section"><h2>Need More Help?</h2><a href="/contact.php" class="btn btn-primary btn-lg">Contact Support</a><a href="/help.php" class="btn btn-outline btn-lg">Back to Help Center</a></div></div></div>
<style>.help-header{background:linear-gradient(135deg,#0654ba,#1e40af);color:white;text-align:center;padding:60px 20px;margin-bottom:40px;border-radius:12px}.help-header h1{margin:0 0 10px 0;font-size:36px}.help-header p{margin:0;font-size:18px;opacity:0.9}.help-content{max-width:1200px;margin:0 auto;padding:0 20px 40px}.help-section{margin-bottom:50px}.help-section h2{font-size:28px;margin-bottom:25px;color:#1f2937;border-bottom:2px solid #0654ba;padding-bottom:10px}.steps{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:25px;margin-top:30px}.step{background:white;padding:25px;border-radius:8px;box-shadow:0 2px 8px rgba(0,0,0,0.1);text-align:center}.step-number{width:50px;height:50px;background:#0654ba;color:white;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:24px;font-weight:bold;margin:0 auto 15px}.step h3{margin:10px 0;color:#1f2937}.help-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:20px;margin-top:20px}.help-item{background:white;padding:25px;border-radius:8px;box-shadow:0 2px 8px rgba(0,0,0,0.1)}.help-item h3{margin-top:0;margin-bottom:15px;color:#1f2937;font-size:20px}.help-item ul,.help-item ol{margin:15px 0;padding-left:25px}.help-item li{margin-bottom:8px;color:#374151}.cta-section{text-align:center;padding:40px;background:linear-gradient(135deg,#f9fafb 0%,#e5e7eb 100%);border-radius:12px;margin-top:40px}.cta-section h2{margin-bottom:20px}.btn-lg{padding:15px 40px;font-size:18px}@media (max-width:768px){.help-grid,.steps{grid-template-columns:1fr}}</style>
<?php includeFooter(); ?>
